# Tugas 5 




K-means merupakan salah satu algoritma yang bersifat unsupervised learning. K-Means memiliki fungsi untuk mengelompokkan data kedalam data cluster. Algoritma ini dapat menerima data tanpa ada label kategori.

K-Means Clustering adalah suatu metode penganalisaan data atau metode Data Mining yang melakukan proses pemodelan unssupervised learning dan menggunakan metode yang mengelompokan data berbagai partisi.

K Means Clustering memiliki objective yaitu meminimalisasi object function yang telah di atur pada proses clasterisasi. Dengan cara minimalisasi variasi antar 1 cluster dengan maksimalisasi variasi dengan data di cluster lainnya.

K means clustering merupakan metode algoritma dasar, yang diterapkan sebagai berikut

Menentukan jumlah cluster

- Secara acak mendistribusikan data cluster
- Menghitung rata rata dari data yang ada di cluster.
- Menggunakan langkah baris 3 kembali sesuai nilai treshold
- Menghitung jarak antara data dan nilai centroid(K means clustering)
- Distance space dapat diimplementasikan untuk menghitung jarak data dan centroid.




In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [3]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
X = df

y = df["variety"]

le = LabelEncoder()

X['variety'] = le.fit_transform(X['variety'])

y = le.transform(y)

y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
X.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

Featuring Scaling

In [6]:
cols = X.columns

In [7]:
from sklearn.preprocessing import MinMaxScaler

ms = MinMaxScaler()

X = ms.fit_transform(X)

In [8]:
X = pd.DataFrame(X, columns=[cols])

In [9]:
X

sepal.length sepal.width petal.length petal.width variety
0       0.222222    0.625000     0.067797    0.041667     0.0
1       0.166667    0.416667     0.067797    0.041667     0.0
2       0.111111    0.500000     0.050847    0.041667     0.0
3       0.083333    0.458333     0.084746    0.041667     0.0
4       0.194444    0.666667     0.067797    0.041667     0.0
..           ...         ...          ...         ...     ...
145     0.666667    0.416667     0.711864    0.916667     1.0
146     0.555556    0.208333     0.677966    0.750000     1.0
147     0.611111    0.416667     0.711864    0.791667     1.0
148     0.527778    0.583333     0.745763    0.916667     1.0
149     0.444444    0.416667     0.694915    0.708333     1.0

[150 rows x 5 columns]

K-Means model with three clusters

In [10]:
from sklearn.cluster import KMeans

# Fit K-means with Scikit
kmeans = KMeans(n_clusters=3, random_state=0) 

# Predict the cluster for all the samples
kmeans.fit(X)

pred = kmeans.predict(X)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


K-Means model parameters study

In [11]:
kmeans.cluster_centers_

array([[0.19611111, 0.595     , 0.07830508, 0.06083333, 0.        ],
       [0.63555556, 0.40583333, 0.77152542, 0.8025    , 1.        ],
       [0.45444444, 0.32083333, 0.55254237, 0.51083333, 0.5       ]])

In [12]:
kmeans.inertia_

7.801559361268047

Check quality of weak classification by the model

In [13]:
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [14]:
labels = kmeans.labels_

# check how many of the samples were correctly labeled
correct_labels = sum(y == labels)

print("Result: %d out of %d samples were correctly labeled." % (correct_labels, y.size))

Result: 50 out of 150 samples were correctly labeled.


In [15]:
print('Accuracy score: {0:0.2f}'. format(correct_labels/float(y.size)))

Accuracy score: 0.33


In [16]:
df2 = pd.DataFrame(X)
df2["cluster"] = pred
df2

sepal.length sepal.width petal.length petal.width variety cluster
0       0.222222    0.625000     0.067797    0.041667     0.0       0
1       0.166667    0.416667     0.067797    0.041667     0.0       0
2       0.111111    0.500000     0.050847    0.041667     0.0       0
3       0.083333    0.458333     0.084746    0.041667     0.0       0
4       0.194444    0.666667     0.067797    0.041667     0.0       0
..           ...         ...          ...         ...     ...     ...
145     0.666667    0.416667     0.711864    0.916667     1.0       1
146     0.555556    0.208333     0.677966    0.750000     1.0       1
147     0.611111    0.416667     0.711864    0.791667     1.0       1
148     0.527778    0.583333     0.745763    0.916667     1.0       1
149     0.444444    0.416667     0.694915    0.708333     1.0       1

[150 rows x 6 columns]